name: Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  print-hello-world: # this is the name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: "echo world"
        